//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4.FileParser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_4.FileParser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} args:.
        /// </summary>
        internal static string ARGS {
            get {
                return ResourceManager.GetString("ARGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument is less than 0..
        /// </summary>
        internal static string ARGUMENT_LESS_ZERO {
            get {
                return ResourceManager.GetString("ARGUMENT_LESS_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string EMPTY_STRING {
            get {
                return ResourceManager.GetString("EMPTY_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String enters in the file - {0} times..
        /// </summary>
        internal static string ENTERS_AMOUNT {
            get {
                return ResourceManager.GetString("ENTERS_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This path &apos;{0}&apos; doesn&apos;t exist..
        /// </summary>
        internal static string FILE_NOT_EXISTS {
            get {
                return ResourceManager.GetString("FILE_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string ONE_ARG {
            get {
                return ResourceManager.GetString("ONE_ARG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESULT:.
        /// </summary>
        internal static string RESULT {
            get {
                return ResourceManager.GetString("RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\..\TextFiles\spec.txt.
        /// </summary>
        internal static string SPEC_FILE {
            get {
                return ResourceManager.GetString("SPEC_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String {0} is null..
        /// </summary>
        internal static string STRING_NULL {
            get {
                return ResourceManager.GetString("STRING_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String {0} is null or empty..
        /// </summary>
        internal static string STRING_NULL_EMPTY {
            get {
                return ResourceManager.GetString("STRING_NULL_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text from File: .
        /// </summary>
        internal static string TEXT_FROM_FILE {
            get {
                return ResourceManager.GetString("TEXT_FROM_FILE", resourceCulture);
            }
        }
    }
}
