//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2.Envelope.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_2.Envelope.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By!.
        /// </summary>
        internal static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to continue?.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envelope {0}..
        /// </summary>
        internal static string Envelope {
            get {
                return ResourceManager.GetString("Envelope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envelope 1 {0} is nested in the envelope 2 {1}..
        /// </summary>
        internal static string Envelope1In2 {
            get {
                return ResourceManager.GetString("Envelope1In2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envelope 2 {0} is nested in the envelope 1 {1}..
        /// </summary>
        internal static string Envelope2In1 {
            get {
                return ResourceManager.GetString("Envelope2In1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Envelope: {0} x {1}).
        /// </summary>
        internal static string EnvelopeSize {
            get {
                return ResourceManager.GetString("EnvelopeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, input the side size of the envelope or input &apos;out&apos; .
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NESTING :.
        /// </summary>
        internal static string Nesting {
            get {
                return ResourceManager.GetString("Nesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Envelope.
        /// </summary>
        internal static string NoEnvelope {
            get {
                return ResourceManager.GetString("NoEnvelope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envelops can&apos;t be nested into each other. {0}-{1}.
        /// </summary>
        internal static string NoEnvelopeInput {
            get {
                return ResourceManager.GetString("NoEnvelopeInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long side &apos;{0}&apos; of the envelope isn&apos;t valid..
        /// </summary>
        internal static string NoLongSize {
            get {
                return ResourceManager.GetString("NoLongSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short side &apos;{0}&apos; of the envelope isn&apos;t valid..
        /// </summary>
        internal static string NoShortSide {
            get {
                return ResourceManager.GetString("NoShortSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve input {0} that is not valid..
        /// </summary>
        internal static string NotValid {
            get {
                return ResourceManager.GetString("NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
    }
}
