//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3.Triangle.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_3.Triangle.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разделитель: &apos;,&apos;.
        /// </summary>
        internal static string Divider {
            get {
                return ResourceManager.GetString("Divider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ============= Triangles list: ===============.
        /// </summary>
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, input triangle parametres or input &apos;out&apos;.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your input is not valid.
        /// </summary>
        internal static string InputNotValid {
            get {
                return ResourceManager.GetString("InputNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to add new triangle?.
        /// </summary>
        internal static string IsContinue {
            get {
                return ResourceManager.GetString("IsContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve input {0} parameters. Must be 4.
        /// </summary>
        internal static string LessParam {
            get {
                return ResourceManager.GetString("LessParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangler parameter {0} can&apos;t be converted to double.
        /// </summary>
        internal static string NoConvert {
            get {
                return ResourceManager.GetString("NoConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name {0} is not valid.
        /// </summary>
        internal static string NoName {
            get {
                return ResourceManager.GetString("NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side {0} is not valid.
        /// </summary>
        internal static string NoSide {
            get {
                return ResourceManager.GetString("NoSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangle can&apos;t be created cause of side sizes.
        /// </summary>
        internal static string NoTriangle {
            get {
                return ResourceManager.GetString("NoTriangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New triangle is null.
        /// </summary>
        internal static string NoTriangleExists {
            get {
                return ResourceManager.GetString("NoTriangleExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. {1}.
        /// </summary>
        internal static string ShowTwoParam {
            get {
                return ResourceManager.GetString("ShowTwoParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Triangle {0}, {2}, {3}, {4}]: {1} cm.
        /// </summary>
        internal static string Triangle {
            get {
                return ResourceManager.GetString("Triangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format: &lt; имя &gt;, &lt; длина стороны &gt;, &lt; длина стороны &gt;, &lt; длина стороны &gt;.
        /// </summary>
        internal static string TriangleFormat {
            get {
                return ResourceManager.GetString("TriangleFormat", resourceCulture);
            }
        }
    }
}
